server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true #当前的微服务是否注册到center当中
    fetchRegistry: false  #是否抓取微服务的信息
spring:
  application:
    name: CRUDSERVICE 
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: ps123456
    driver-class-name: com.mysql.jdbc.Driver    